CREATE DATABASE miage CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE `miage`.`data`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
    `name` TEXT NOT NULL ,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `last_update` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `data` JSON NOT NULL ,
    PRIMARY KEY(`id`)
);